Update for Wed Nov  7 15:02:59 2018

diff --git a/distros/S/Shell-Cmd/t/bin/fail b/distros/S/Shell-Cmd/t/bin/fail
--- a/distros/S/Shell-Cmd/t/bin/fail
+++ b/distros/S/Shell-Cmd/t/bin/fail
@@ -1,7 +1,9 @@
-#!/usr/bin/perl
-$| = 1;
+#!/bin/sh
+arg=$1
+warn=$2
 
-print "This is the 'fail' command\n";
-warn  "It will give an error\n";
-print "It will fail\n";
-exit 10;
+echo "This is the 'fail' command stdout with argument: $arg"
+if [ ! -z "$warn" ]; then
+   echo "This is the 'fail' command stderr with argument: $arg" >&2
+fi
+exit 10
diff --git a/distros/S/Shell-Cmd/t/bin/fail_on_2 b/distros/S/Shell-Cmd/t/bin/fail_on_2
--- a/distros/S/Shell-Cmd/t/bin/fail_on_2
+++ b/distros/S/Shell-Cmd/t/bin/fail_on_2
@@ -1,9 +1,10 @@
-#!/usr/bin/perl
-$| = 1;
-$i = $ARGV[0] || '';
+#!/bin/sh
+i=$1
 
-print "Input: $i\n";
-if ($i eq '2') {
-   exit 10;
-}
-exit 0;
+if [ $i -eq 2 ]; then
+   echo "fail_on_2 fails on 2"
+   exit 10
+else
+   echo "fail_on_2 succeeds on $i"
+   exit 0
+fi
diff --git a/distros/S/Shell-Cmd/t/bin/fail_twice b/distros/S/Shell-Cmd/t/bin/fail_twice
--- a/distros/S/Shell-Cmd/t/bin/fail_twice
+++ b/distros/S/Shell-Cmd/t/bin/fail_twice
@@ -1,22 +1,21 @@
-#!/usr/bin/perl
-$| = 1;
+#!/bin/sh
 
-if ( ! -f "fail_twice_1" ) {
-   print "Running first time\n";
-   open(OUT, ">fail_twice_1");
-   close(OUT);
-   warn  "Failing first time\n";
-   exit 20;
-}
+dir=$1
 
-if ( ! -f "fail_twice_2" ) {
-   print "Running second time\n";
-   open(OUT, ">fail_twice_2");
-   close(OUT);
-   warn "Failing second time\n";
-   exit 21;
-}
+if [ ! -f "$dir/fail_twice.1.flag" ]; then
+   echo "fail_twice running first time"
+   touch $dir/fail_twice.1.flag
+   echo "fail_twice failing first time" >&2
+   exit 20
+fi
 
-print "Running third time\n";
-unlink ("fail_twice_1","fail_twice_2");
-exit 0;
+if [ ! -f "$dir/fail_twice.2.flag" ]; then
+   echo "fail_twice running second time"
+   touch $dir/fail_twice.2.flag
+   echo "fail_twice failing second time" >&2
+   exit 21
+fi
+
+echo "fail_twice running third time"
+rm -f $dir/fail_twice.*.flag
+exit 0
