Update for Wed Apr 16 05:06:56 2025

diff --git a/distros/A/App-Greple-xlate/script/xlate b/distros/A/App-Greple-xlate/script/xlate
--- a/distros/A/App-Greple-xlate/script/xlate
+++ b/distros/A/App-Greple-xlate/script/xlate
@@ -65,7 +65,7 @@ define pod <<"=cut"
 
 =head1 VERSION
 
-    Version 0.9908
+    Version 0.9909
 
 =cut
 
@@ -166,8 +166,9 @@ docker_status() {
 ##
 ## read .xlaterc
 ##
-declare -a rcpath=($HOME)
+declare -a rcpath=(.)
 [[ $topdir && $topdir != $pwd ]] && rcpath+=($topdir)
+[[ $HOME != $pwd ]] && rcpath+=($HOME)
 for dir in ${rcpath[@]}
 do
     rc="$dir/.xlaterc"
@@ -184,7 +185,7 @@ if [[ $topdir && $topdir != $pwd ]]
 then
     volume="$topdir"
 fi
-while getopts :dq${DOCKER_OPT:=dURAI:E:WHP:O:BV:GN:KSALCD} OPT
+while getopts :dq${DOCKER_OPT:=dJ:URAI:E:WHP:O:BV:GN:KSALCD} OPT
 do
     [[ $XLATE_RUNNING_ON_DOCKER ]] && break
     case $OPT in
@@ -204,6 +205,7 @@ do
 	B) interactive= ;;
 
 	# mount related options
+	J) workdir="$OPTARG" ;;
 	U) mount= ;;
 	R) mount_mode=ro ;;
 	V) volumes+=("$OPTARG") ;;
@@ -373,6 +375,16 @@ do
 done	
 shift $((OPTIND - 1))
 
+find_gmake() {
+    local make
+    (( $# == 0 )) && set make gmake gnumake
+    for make in $@
+    do
+	[[ $($make --version) =~ GNU ]] && { echo $make; return 0; }
+    done
+    return 1
+}
+
 ##
 ## Make
 ##
@@ -391,7 +403,8 @@ then
 	fi
     done
     unset MAKELEVEL
-    exec make -f $share/XLATE.mk \
+    gmake=$(find_gmake) || { warn "GNU Make is required."; exit 1; }
+    exec $gmake -f $share/XLATE.mk \
 	 ${dryrun:+-n} \
 	 XLATE_LANG=\""$tgt_lang"\" \
 	 XLATE_DEBUG=$debug \
@@ -407,7 +420,7 @@ fi
 
 if [[ ! $tgt_lang ]]
 then
-    warn "-t option is required."
+    warn "$myname: -t option is required."
     exit 1
 fi
 
@@ -427,17 +440,17 @@ option+=(--xlate-engine="$engine")
 option+=(--xlate-to="$tgt_lang" --xlate-format="$format" --xlate-cache=yes)
 option+=(--all)
 
-[ "$base_lang"      ] && option+=(--xlate-from "$base_lang")
-[ "$use_api" == yes ] || use_clipboard=yes
-[ "$check"   == yes ] || option+=(--xlate${use_clipboard:+-labor})
-[ "$wrap"           ] && option+=(--xlate-fold-line --xlate-fold-width=$wrap)
-[ "$debug"   == yes ] && option+=(-dmo)
-[ "$refresh" == yes ] && option+=(--xlate-cache=clear)
-[ "$update"  == yes ] && option+=(--xlate-update)
-[ "$silent"  == yes ] && option+=(--no-xlate-progress)
-[ "$max"            ] && option+=(--xlate-maxlen="$max")
-[ "$maskfile"       ] && option+=(--xlate-setopt "maskfile=$maskfile")
-[ "$glossary"       ] && option+=(--xlate-glossary "$glossary")
+[[ $base_lang      ]] && option+=(--xlate-from "$base_lang")
+[[ $use_api == yes ]] || use_clipboard=yes
+[[ $check   == yes ]] || option+=(--xlate${use_clipboard:+-labor})
+[[ $wrap           ]] && option+=(--xlate-fold-line --xlate-fold-width=$wrap)
+[[ $debug   == yes ]] && option+=(-dmo)
+[[ $refresh == yes ]] && option+=(--xlate-cache=clear)
+[[ $update  == yes ]] && option+=(--xlate-update)
+[[ $silent  == yes ]] && option+=(--no-xlate-progress)
+[[ $max            ]] && option+=(--xlate-maxlen="$max")
+[[ $maskfile       ]] && option+=(--xlate-setopt "maskfile=$maskfile")
+[[ $glossary       ]] && option+=(--xlate-glossary "$glossary")
 
 declare -a area
 case $1 in
@@ -628,9 +641,9 @@ rules, refer to the F<XLATE.mk> file in the xlate library directory.
 =head2 XLATERC File
 
 The F<.xlaterc> file allows you to set default options for the
-C<xlate> command.  This file is searched in the Git top directory and
-the current directory.  If found, its contents are applied before any
-command-line options.
+C<xlate> command.  This file is searched in the user's home directory,
+Git top directory and the current directory.  If found, its contents
+are applied before any command-line options.
 
 Each line in the C<.xlaterc> file should contain a valid C<xlate>
 command option.  Lines starting with C<#> are treated as comments and
@@ -836,6 +849,14 @@ Repeatable.
 
 Specify Docker image name.  If it begins with a colon (C<:>), it is
 treated as a version of the default image.
+
+=begin comment
+
+=item B<-J> I<directory>
+
+Specify the working directory (default: C</work>).
+
+=end comment
 
 =item B<-B>
 
