Update for Mon Sep  8 05:07:41 2025

diff --git a/distros/N/Net-Ping/Makefile.PL b/distros/N/Net-Ping/Makefile.PL
--- a/distros/N/Net-Ping/Makefile.PL
+++ b/distros/N/Net-Ping/Makefile.PL
@@ -67,7 +67,13 @@ sub depend {
 README : lib/Net/Ping.pm
 	pod2text lib/Net/Ping.pm > README
 release : dist
-	git tag \$(VERSION)
+	if test \"\$(shell git rev-parse --abbrev-ref HEAD)\" != \"master\" || \\
+           test \"\$(shell git diff --raw)\" != \"\" || \\
+           test \"\$(shell git diff --cached --raw)\" != \"\" ; then \\
+          echo 'You are not on a clean master branch, aborting.'; \\
+          exit 1; \\
+	fi
+	-git tag -f \$(VERSION)
 	cpan-upload \$(DISTVNAME).tar\$(SUFFIX)
 	git push
 	git push --tags
diff --git a/distros/S/Set-Object/Makefile.PL b/distros/S/Set-Object/Makefile.PL
--- a/distros/S/Set-Object/Makefile.PL
+++ b/distros/S/Set-Object/Makefile.PL
@@ -52,10 +52,23 @@ package MY;
 
 sub depend {
   "
+release-test : dist
+	if test \"\$(shell git rev-parse --abbrev-ref HEAD)\" != \"master\" || \\
+           test \"\$(shell git status --porcelain)\" != \"\" ; then \\
+          echo 'You are not on a clean master branch, aborting.'; \\
+          exit 1 ; \\
+	fi
+	echo git tag \$(VERSION)
+	echo cpan-upload \$(DISTVNAME).tar\$(SUFFIX)
+	echo git push
+	echo git push --tags
+
 release : dist
-	-git commit -am\"release \$(VERSION)\"
-	echo -n continue?
-	read y
+	if test \"\$(shell git rev-parse --abbrev-ref HEAD)\" != \"master\" || \\
+           test \"\$(shell git status --porcelain)\" != \"\" ; then \\
+          echo 'You are not on a clean master branch, aborting.'; \\
+          exit 1; \\
+	fi
 	git tag \$(VERSION)
 	cpan-upload \$(DISTVNAME).tar\$(SUFFIX)
 	git push
