Update for Thu Oct 30 14:43:19 2025

diff --git a/distros/O/OrePAN2-S3/bin/orepan2-s3 b/distros/O/OrePAN2-S3/bin/orepan2-s3
--- a/distros/O/OrePAN2-S3/bin/orepan2-s3
+++ b/distros/O/OrePAN2-S3/bin/orepan2-s3
@@ -7,13 +7,16 @@ usage() {
     cat <<EOF
 Usage: $0 options command args
 
+Script for maintaining your DarkPAN repository.
+
 Options
 -------
   -h, --help             Display this help message
+  -l, --log-level        logging level, error, warn, info, debug, trace
   -P, --prefix           Path prefix in the S3 bucket
   -b, --bucket           S3 Bucket Name
   -p, --profile          AWS Profile
-  -N, --profile-name     orepan2-add config profile name
+  -n, --name             orepan2-add config profile name
   -x, --no-invalidate    Do not invalidate cache
   -c, --config           Config file name (default: .orepan2-s3.json)
   -r, --region           AWS region (default: us-east-1)
@@ -25,6 +28,8 @@ Options
 Commands
 --------
 add {file}               Add a tarball to the repository
+delete {file}            Delete a distribution
+index                    Update index.html
 invalidate               Invalidate CloudFront cache
 help                     Display this help message
 
@@ -35,7 +40,10 @@ Notes
 
 2. default configuration file is .orepan2-s3.json and should be in your home directory
 
-3. you must provide either -t TAG-VALUE or -d DISTRIBUTIO-id
+3. you must provide either -t TAG-VALUE or -d DISTRIBUTION-ID or set
+the "DistributionID" key in your configuration file if your are using CloudFront
+
+4. See perldoc OrePAN2::S3 for more details
 
 EOF
 
@@ -48,9 +56,17 @@ find_config_name() {
     local config_file="$1"
     local config_profile="${2:-default}"
 
-    local path_prefix=".$config_profile.index"
+    if ! jq -e '(.default | type) == "object"' $config_file >/dev/null; then
+        config_profile=$(jq -r ".$2" $config_file)
+        if ! jq -e '(.'$config_profile' | type ) == "object"' $config_file >/dev/null; then
+            echo >&2 "ERROR: can't determine config profile"
+            exit 1;
+        fi
+    fi
+    
+    local path_prefix=".${config_profile}.index"
 
-    local index=$(cat $config_file | jq -r "$path_prefix?//\"\"")
+    local index=$(cat $config_file | jq -r "$path_prefix? //\"\"")
     
     if test -n "$index"; then
         echo $config_profile
@@ -63,12 +79,12 @@ find_config() {
     local config_file="$1"
     local config_profile="${2:-default}"
 
-    config_profile=$(find_config_name "$config_file" "$config_profile");
+    local config_profile=$(find_config_name "$config_file" "$config_profile");
     test -n "$config_profile" && config_profile=".$config_profile"
 
-    local path="$config_profile.index? // \"\""
+    local path="$config_profile.index? //\"\""
 
-    cat $config_file | jq -r  "$path"
+    cat $config_file | jq -r "$path"
 }
 
 ########################################################################
@@ -79,7 +95,7 @@ upload_artifacts() {
     
     local config="$1"
 
-    if [[ -n "$config" && -n $(echo "$config" | jq -r '.files?//""') ]]; then
+    if [[ -n "$config" && -n $(echo "$config" | jq -r '.files? //""') ]]; then
         local aws_profile="$AWS_PROFILE";
 
         if test -n "$aws_profile"; then
@@ -89,8 +105,8 @@ upload_artifacts() {
         echo "$config" | jq -r '.files| to_entries[] | "\(.key) \(.value)"' |
             while read -r src dest; do
                 if test -e "$src"; then
-                    echo "uploading $src to => s3://$bucket$dest" >&2
-                    aws s3 $aws_profile cp "$src" "s3://$bucket$dest" >&2
+                    echo >&2 "uploading $src to => s3://$bucket$dest" >&2
+                    aws s3 $aws_profile $QUIET cp "$src" "s3://$bucket$dest" >&2
                 else
                     echo "$src not found...skipping" >&2
                 fi
@@ -161,7 +177,7 @@ create_index() {
     local config=$(find_config "$CONFIG_FILE" "$PROFILE_NAME")
 
     if test -n "$PROFILE_NAME"; then
-        config_profile="--profile $PROFILE_NAME"
+        config_profile="--profile-name $PROFILE_NAME"
     fi
 
     local template="${TEMPLATE:-}"
@@ -172,20 +188,25 @@ create_index() {
         index_template=$(echo $config | jq -r '.template')
         
         if [[ -n "$index_template" && -e "$index_template" ]]; then
-            $template="--template $index_template"
+            template="--template $index_template"
         fi
     fi
 
     if test -e "$index_template"; then
-        test -n "$VERBOSE" && echo "creating index from template $index_template..."
+        echo >&2 "creating and uploading index.html from template $index_template..."
     fi
 
-    orepan2-s3-index $template $config_profile -c $CONFIG_FILE create >$index
+    LOG_LEVEL=${LOG_LEVEL:-info}
 
-    test -n "$VERBOSE" && echo "uploading new index..."
-    orepan2-s3-index $config_profile -c $CONFIG_FILE upload $index
+    orepan2-s3-index $template $config_profile -c $CONFIG_FILE -u --log-level $LOG_LEVEL create
+    
+    if test -n "$FILE"; then
+        echo >&2 "extracting and uploading documentation..."
 
-    test -n "$VERBOSE" && echo "looking for artifacts to upload..."
+        orepan2-s3-index $config_profile -c $CONFIG_FILE -u create-docs $FILE
+    fi
+
+    echo >&2 "looking for artifacts to upload..."
     upload_artifacts "$config"
 
     rm $index
@@ -205,8 +226,41 @@ invalidate_cache() {
 ########################################################################
 cleanup() {
 ########################################################################
-    test -n "$VERBOSE" && echo "cleaning up temp directory..."
+    echo >&2 "cleaning up temp directory..."
     test -n "$TEMP_DIR" && rm -rf "$TEMP_DIR"
+}
+
+########################################################################
+sync_local() {
+########################################################################
+    # Create a temporary directory
+    TEMP_DIR=$(mktemp -d)
+
+    test -n "$VERBOSE" && echo "syncing s3://$BUCKET/$PATH_PREFIX => $TEMP_DIR/$PATH_PREFIX..."
+
+    # Sync S3 contents to the temporary directory
+    $AWS s3 sync "s3://$BUCKET/$PATH_PREFIX" "$TEMP_DIR/$PATH_PREFIX" $QUIET --profile "$AWS_PROFILE"
+}
+
+########################################################################
+index() {
+########################################################################
+    echo >&2 "indexing OrePAN repository..." >&2
+    orepan2-indexer "$TEMP_DIR/$PATH_PREFIX"
+}
+
+########################################################################
+index_and_sync_remote() {
+########################################################################
+    index
+    sync_remote
+}
+
+########################################################################
+sync_remote() {
+########################################################################
+    echo >&2 "syncing $TEMP_DIR/$PATH_PREFIX => s3://$BUCKET/$PATH_PREFIX..."
+    $AWS s3 sync "$TEMP_DIR/$PATH_PREFIX" "s3://$BUCKET/$PATH_PREFIX" $QUIET --profile "$AWS_PROFILE"
 }
 
 ########################################################################
@@ -222,18 +276,9 @@ add() {
         exit 1;
     fi
 
-    # Create a temporary directory
-    TEMP_DIR=$(mktemp -d)
+    sync_local;
 
-    # Set an exit trap to always run cleanup
-    trap cleanup EXIT
-
-    test -n "$VERBOSE" && echo "syncing s3://$BUCKET/$PATH_PREFIX => $TEMP_DIR/$PATH_PREFIX..."
-
-    # Sync S3 contents to the temporary directory
-    $AWS s3 sync "s3://$BUCKET/$PATH_PREFIX" "$TEMP_DIR/$PATH_PREFIX" --profile "$AWS_PROFILE"
-
-    test -n "$VERBOSE" && echo "adding $FILE to OrePAN package index..."
+    echo >&2 "injecting $FILE to OrePAN package index..."
 
     orepan2-inject "$FILE" "$TEMP_DIR/$PATH_PREFIX"
 
@@ -243,11 +288,7 @@ add() {
         exit 1
     fi
 
-    test -n "$VERBOSE" && echo "indexing OrePAN repository..." >&2
-    orepan2-indexer "$TEMP_DIR/$PATH_PREFIX"
-
-    test -n "$VERBOSE" && echo "syncing $TEMP_DIR/$PATH_PREFIX => s3://$BUCKET/$PATH_PREFIX..."
-    $AWS s3 sync "$TEMP_DIR/$PATH_PREFIX" "s3://$BUCKET/$PATH_PREFIX" --profile "$AWS_PROFILE"
+    sync_remote;
 }
 
 ########################################################################
@@ -260,11 +301,11 @@ set_defaults() {
     test -z "$AWS_REGION" && AWS_REGION=$(echo "$config" | jq -r '.AWS.region // "us-east-1"')
     test -z "$DISTRIBUTION_ID" && DISTRIBUTION_ID=$(echo "$config" | jq -r '.CloudFront.DistributionId // ""')
     test -z "$PATH_PREFIX" && PATH_PREFIX=$(echo "$config" | jq -r '.AWS.prefix // ""')
-    test -z "$BUCKET" && BUCKET=$(echo "$config" | jq -r '.AWS.bucket // ""')
+    test -z "$BUCKET" && BUCKET=$(echo "$config" | jq -r '.AWS.bucket? // ""')
 
     AWS_ACCOUNT=$(echo "$CONFIG" | jq -r '.AWS.account // ""')
     test -z "$AWS_ACCOUNT" && AWS_ACCOUNT=$($AWS sts get-caller-identity --query 'Account' --output text --profile "$AWS_PROFILE")
-
+    CONFIG=$config
 }
 
 ########################################################################
@@ -286,10 +327,13 @@ NOT_OK="ERROR"
 OK=""
 INDEX_TEMPLATE=""
 VERBOSE=""
+QUIET="--quiet"
+TEMP_DIR=""
+LOG_LEVEL=""
 
 # Parse command-line options using getopt
-OPTIONS=$(getopt -o hp:t:P:c:d:b:xn:T:v \
-                 --long verbose,help,profile:,name:,tag:,template:,prefix:,config:,distribution-id:,bucket:,no-invalidate -- "$@")
+OPTIONS=$(getopt -o hl:p:t:P:c:d:b:xn:T:v \
+                 --long log-level:,verbose,help,profile:,name:,tag:,template:,prefix:,config:,distribution-id:,bucket:,no-invalidate -- "$@")
 
 if [ $? -ne 0 ]; then
     echo "$NOT_OK Error parsing options." >&2
@@ -307,7 +351,14 @@ while true; do
 
         -v|--verbose)
             VERBOSE="1";
-            shift 1
+            QUIET="";
+            LOG_LEVEL=trace;
+            shift 1;
+            ;;
+
+        -l|--log-level)
+            LOG_LEVEL="$2";
+            shift 2;
             ;;
 
         -c|--config)
@@ -362,6 +413,10 @@ while true; do
     esac
 done
 
+# Set an exit trap to always run cleanup
+trap cleanup EXIT
+
+
 COMMAND=${1:-}
 
 test -z "$COMMAND" && COMMAND="help"
@@ -393,8 +448,9 @@ INVALIDATION_PATHS=()
 INVALIDATION_PATHS+=("/$PATH_PREFIX/modules/02packages.details.txt.gz")
 INVALIDATION_PATHS+=("/$PATH_PREFIX/orepan2-cache.json")
 INVALIDATION_PATHS+=("/index.html")
+INVALIDATION_PATHS+=("/docs/*")
 
-for p in $(cat $CONFIG_FILE | jq -r '.default.CloudFront.InvalidationPaths?//[]|.[]|.'); do 
+for p in $(echo $CONFIG | jq -r '.CloudFront.InvalidationPaths? //[]|.[]|.'); do 
     test -n "$VERBOSE" && echo "adding custom invalidation path: $p" >&2
     INVALIDATION_PATHS+=("$p")
 done
@@ -415,6 +471,35 @@ case "$COMMAND" in
             test -n "$VERBOSE" && echo "invalidating cache...\n${INVALIDATION_PATHS[@]}"
             invalidate_cache
         fi
+        ;;
+
+    delete)
+        if test -z "$FILE"; then
+            echo "$NOT_OK no file specified"
+            usage
+        fi
+        
+        $AWS s3 rm s3://$BUCKET/$PATH_PREFIX/authors/id/D/DU/DUMMY/$FILE --profile $AWS_PROFILE
+        sync_local;
+
+        index_and_sync_remote;
+
+        FILE="";
+
+        create_index;
+
+        if test -z "$NO_INVALIDATE"; then
+            if test -n "$DISTRIBUTION_ID"; then
+                test -n "$VERBOSE" && echo "invalidating cache...\n${INVALIDATION_PATHS[@]}"
+                invalidate_cache
+            fi
+        fi
+
+        ;;
+
+    index)
+        create_index;
+        invalidate_cache;
         ;;
 
     add)
